# Generated by Django 3.0.8 on 2020-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.TextField()),
                ('chart', models.ImageField(default='default.jpg', upload_to='sample_charts')),
                ('description', models.TextField()),
            ],
        ),
    ]
