# Generated by Django 3.0.8 on 2020-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsample',
            name='language',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
