# Generated by Django 3.0.8 on 2020-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_codingsample_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingsample',
            name='chart',
            field=models.ImageField(default='default.svg', upload_to='sample_charts'),
        ),
    ]
