# Generated by Django 3.0.8 on 2020-08-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200729_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsample',
            name='description_picture',
            field=models.ImageField(null=True, upload_to='sample_description_images'),
        ),
    ]
